version: "3"
services:
  db:
    image: mariadb:10.0.33
    environment:
      MYSQL_ROOT_PASSWORD: zdf£$bsese4z6Tw4
      MYSQL_DATABASE: dev_test
      MYSQL_USER: dev_test
      MYSQL_PASSWORD: xr5dr6nne47BEDEB
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 33060:3306
  app:
    build:
      context: src
    volumes:
      - ./src:/usr/src
